# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dave-tigre/Documents/git/pi_station

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dave-tigre/Documents/git/pi_station

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dave-tigre/Documents/git/pi_station/CMakeFiles /home/dave-tigre/Documents/git/pi_station/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dave-tigre/Documents/git/pi_station/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WeatherWidget

# Build rule for target.
WeatherWidget: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WeatherWidget
.PHONY : WeatherWidget

# fast build rule for target.
WeatherWidget/fast:
	$(MAKE) -f CMakeFiles/WeatherWidget.dir/build.make CMakeFiles/WeatherWidget.dir/build
.PHONY : WeatherWidget/fast

#=============================================================================
# Target rules for targets named pi_station

# Build rule for target.
pi_station: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pi_station
.PHONY : pi_station

# fast build rule for target.
pi_station/fast:
	$(MAKE) -f CMakeFiles/pi_station.dir/build.make CMakeFiles/pi_station.dir/build
.PHONY : pi_station/fast

#=============================================================================
# Target rules for targets named WeatherWidget_autogen

# Build rule for target.
WeatherWidget_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WeatherWidget_autogen
.PHONY : WeatherWidget_autogen

# fast build rule for target.
WeatherWidget_autogen/fast:
	$(MAKE) -f CMakeFiles/WeatherWidget_autogen.dir/build.make CMakeFiles/WeatherWidget_autogen.dir/build
.PHONY : WeatherWidget_autogen/fast

#=============================================================================
# Target rules for targets named pi_station_autogen

# Build rule for target.
pi_station_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pi_station_autogen
.PHONY : pi_station_autogen

# fast build rule for target.
pi_station_autogen/fast:
	$(MAKE) -f CMakeFiles/pi_station_autogen.dir/build.make CMakeFiles/pi_station_autogen.dir/build
.PHONY : pi_station_autogen/fast

WeatherWidget_autogen/mocs_compilation.o: WeatherWidget_autogen/mocs_compilation.cpp.o

.PHONY : WeatherWidget_autogen/mocs_compilation.o

# target to build an object file
WeatherWidget_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/WeatherWidget.dir/build.make CMakeFiles/WeatherWidget.dir/WeatherWidget_autogen/mocs_compilation.cpp.o
.PHONY : WeatherWidget_autogen/mocs_compilation.cpp.o

WeatherWidget_autogen/mocs_compilation.i: WeatherWidget_autogen/mocs_compilation.cpp.i

.PHONY : WeatherWidget_autogen/mocs_compilation.i

# target to preprocess a source file
WeatherWidget_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/WeatherWidget.dir/build.make CMakeFiles/WeatherWidget.dir/WeatherWidget_autogen/mocs_compilation.cpp.i
.PHONY : WeatherWidget_autogen/mocs_compilation.cpp.i

WeatherWidget_autogen/mocs_compilation.s: WeatherWidget_autogen/mocs_compilation.cpp.s

.PHONY : WeatherWidget_autogen/mocs_compilation.s

# target to generate assembly for a file
WeatherWidget_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/WeatherWidget.dir/build.make CMakeFiles/WeatherWidget.dir/WeatherWidget_autogen/mocs_compilation.cpp.s
.PHONY : WeatherWidget_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/pi_station.dir/build.make CMakeFiles/pi_station.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/pi_station.dir/build.make CMakeFiles/pi_station.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/pi_station.dir/build.make CMakeFiles/pi_station.dir/main.cpp.s
.PHONY : main.cpp.s

pi_station_autogen/mocs_compilation.o: pi_station_autogen/mocs_compilation.cpp.o

.PHONY : pi_station_autogen/mocs_compilation.o

# target to build an object file
pi_station_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/pi_station.dir/build.make CMakeFiles/pi_station.dir/pi_station_autogen/mocs_compilation.cpp.o
.PHONY : pi_station_autogen/mocs_compilation.cpp.o

pi_station_autogen/mocs_compilation.i: pi_station_autogen/mocs_compilation.cpp.i

.PHONY : pi_station_autogen/mocs_compilation.i

# target to preprocess a source file
pi_station_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/pi_station.dir/build.make CMakeFiles/pi_station.dir/pi_station_autogen/mocs_compilation.cpp.i
.PHONY : pi_station_autogen/mocs_compilation.cpp.i

pi_station_autogen/mocs_compilation.s: pi_station_autogen/mocs_compilation.cpp.s

.PHONY : pi_station_autogen/mocs_compilation.s

# target to generate assembly for a file
pi_station_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/pi_station.dir/build.make CMakeFiles/pi_station.dir/pi_station_autogen/mocs_compilation.cpp.s
.PHONY : pi_station_autogen/mocs_compilation.cpp.s

pistation.o: pistation.cpp.o

.PHONY : pistation.o

# target to build an object file
pistation.cpp.o:
	$(MAKE) -f CMakeFiles/pi_station.dir/build.make CMakeFiles/pi_station.dir/pistation.cpp.o
.PHONY : pistation.cpp.o

pistation.i: pistation.cpp.i

.PHONY : pistation.i

# target to preprocess a source file
pistation.cpp.i:
	$(MAKE) -f CMakeFiles/pi_station.dir/build.make CMakeFiles/pi_station.dir/pistation.cpp.i
.PHONY : pistation.cpp.i

pistation.s: pistation.cpp.s

.PHONY : pistation.s

# target to generate assembly for a file
pistation.cpp.s:
	$(MAKE) -f CMakeFiles/pi_station.dir/build.make CMakeFiles/pi_station.dir/pistation.cpp.s
.PHONY : pistation.cpp.s

weatherwidget.o: weatherwidget.cpp.o

.PHONY : weatherwidget.o

# target to build an object file
weatherwidget.cpp.o:
	$(MAKE) -f CMakeFiles/WeatherWidget.dir/build.make CMakeFiles/WeatherWidget.dir/weatherwidget.cpp.o
.PHONY : weatherwidget.cpp.o

weatherwidget.i: weatherwidget.cpp.i

.PHONY : weatherwidget.i

# target to preprocess a source file
weatherwidget.cpp.i:
	$(MAKE) -f CMakeFiles/WeatherWidget.dir/build.make CMakeFiles/WeatherWidget.dir/weatherwidget.cpp.i
.PHONY : weatherwidget.cpp.i

weatherwidget.s: weatherwidget.cpp.s

.PHONY : weatherwidget.s

# target to generate assembly for a file
weatherwidget.cpp.s:
	$(MAKE) -f CMakeFiles/WeatherWidget.dir/build.make CMakeFiles/WeatherWidget.dir/weatherwidget.cpp.s
.PHONY : weatherwidget.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... WeatherWidget"
	@echo "... pi_station"
	@echo "... WeatherWidget_autogen"
	@echo "... pi_station_autogen"
	@echo "... WeatherWidget_autogen/mocs_compilation.o"
	@echo "... WeatherWidget_autogen/mocs_compilation.i"
	@echo "... WeatherWidget_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pi_station_autogen/mocs_compilation.o"
	@echo "... pi_station_autogen/mocs_compilation.i"
	@echo "... pi_station_autogen/mocs_compilation.s"
	@echo "... pistation.o"
	@echo "... pistation.i"
	@echo "... pistation.s"
	@echo "... weatherwidget.o"
	@echo "... weatherwidget.i"
	@echo "... weatherwidget.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

